---
apiVersion: v1
kind: Service
metadata:
  name: mock-endpoint-service
  labels:
    app: mock-endpoint
spec:
  type: NodePort
  ports:
  - port: 4500
    nodePort: 30001
    protocol: TCP
  selector:
    app: mock-endpoint
